'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace My

    Partial Friend Class MyApplication

        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>
        Public Sub New()
            MyBase.New(Global.Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows)
            Me.IsSingleInstance = False
            Me.EnableVisualStyles = True
            Me.SaveMySettingsOnExit = True
            Me.ShutDownStyle = Global.Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses
            ' Register global handlers here — before any WinForms handle/control is created
            ' (including the splash screen). SetUnhandledExceptionMode throws if called later.
            AddHandler Global.System.Windows.Forms.Application.ThreadException, AddressOf OnUiThreadException
            Global.System.Windows.Forms.Application.SetUnhandledExceptionMode(
                Global.System.Windows.Forms.UnhandledExceptionMode.CatchException)
            AddHandler Global.System.AppDomain.CurrentDomain.UnhandledException, AddressOf OnDomainUnhandledException
        End Sub

        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>
        Protected Overrides Sub OnCreateMainForm()
            Me.MainForm = Global.WindowsApplication1.Menü
        End Sub

        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>
        Protected Overrides Sub OnCreateSplashScreen()
            Me.SplashScreen = Global.WindowsApplication1.Begruessung
        End Sub

    End Class

End Namespace
